/** @vitest-environment jsdom */
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import UsagePanel from "../app/console/usage-panel";
import {withZh} from "./test-i18n";
vi.mock("@/components/echart",()=>({EChart:({option,testId}:{option:unknown;testId:string})=><div data-testid={testId} data-option={JSON.stringify(option)}/>}));
vi.mock("@/components/rbac/viewer-context",()=>({useViewer:()=>({userId:"self",signedIn:true,roles:["user"]})}));
vi.mock("next/navigation",()=>({usePathname:()=>"/app/usage",useRouter:()=>({push:vi.fn()})}));
function view(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{withZh(<UsagePanel/>)}</QueryClientProvider>)}
function summary(requests=0){const total={requests,confirmed:requests,pending:0,voided:0,amount_minor:requests*1_000_000,prompt_tokens:requests*2,completion_tokens:requests*3,reasoning_tokens:0};return{totals:total,daily:requests?[{...total,key:"2026-10-10"}]:[],keys:requests?[{...total,key:"key_alpha"}]:[],models:requests?[{...total,key:"echo"}]:[],time_zone:"Asia/Shanghai",generated_at:"2026-10-10T00:00:00Z"}}
describe("full scope usage report",()=>{
 afterEach(()=>{cleanup();vi.unstubAllGlobals()});
 beforeEach(()=>{window.history.replaceState(null,"","/app/usage");vi.stubGlobal("fetch",vi.fn(async()=>({ok:true,json:async()=>summary()})))});
 it("shows real zero only after a successful summary",async()=>{view();await waitFor(()=>expect(screen.getByTestId("usage-stat-requests").textContent).toBe("0"));expect(screen.getAllByText("暂无用量").length).toBeGreaterThan(0)});
 it("failed reads show unknown and retry, not an empty report",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>({ok:false,json:async()=>({error:{message:"failure"}})})));view();await waitFor(()=>expect(screen.getByTestId("list-resource-usage").getAttribute("data-list-phase")).toBe("error"));expect(screen.getByTestId("usage-stat-requests").textContent).toBe("—");expect(screen.queryByText("暂无用量")).toBeNull();expect(screen.getByText("重试读取")).toBeTruthy()});
 it("uses 230 server aggregated records for cards, charts and Key totals",async()=>{const fetcher=vi.fn(async(_input:unknown)=>({ok:true,json:async()=>summary(230)}));vi.stubGlobal("fetch",fetcher);view();await waitFor(()=>expect(screen.getByTestId("usage-stat-requests").textContent).toBe("230"));expect(screen.getByTestId("usage-stat-spend").textContent).toBe("$230.00");expect(screen.getByTestId("usage-key-amount-key_alpha").textContent).toBe("$230.00");expect(screen.getByTestId("usage-trend-chart").getAttribute("data-option")).toContain("230000000");expect(fetcher.mock.calls.every(([url])=>!String(url).includes("limit=100"))).toBe(true)});
 it("consumes model/Key request-tab context in the same page",async()=>{window.history.replaceState(null,"","/app/usage?tab=requests&public_model_id=echo&api_key_id=key_alpha");const fetcher=vi.fn(async(input:unknown)=>({ok:true,json:async()=>String(input).includes("/requests?")?{items:[{request_id:"original_req",public_model_id:"echo",result:"succeeded",customer_amount_minor:1000,started_at:"2026-10-10T00:00:00Z"}],next_cursor:""}:summary(230)}));vi.stubGlobal("fetch",fetcher);view();await waitFor(()=>expect(screen.getByText("original_req")).toBeTruthy());const requests=fetcher.mock.calls.map(v=>String(v[0])).find(v=>v.includes("/requests?"));expect(requests).toContain("public_model_id=echo");expect(requests).toContain("api_key_id=key_alpha");expect(screen.getByRole("link",{name:/2026/}).getAttribute("href")).toContain("/app/usage/requests/original_req")});
 it("keeps other readable Key choices when one Key is selected",async()=>{window.history.replaceState(null,"","/app/usage?api_key_id=key_alpha");vi.stubGlobal("fetch",vi.fn(async()=>({ok:true,json:async()=>({...summary(230),facets:{keys:["key_alpha","key_beta"],models:["echo","other"]},key_labels:{key_alpha:"Production",key_beta:"Backup"}})})));view();await screen.findByRole("option",{name:"Production"});expect(screen.getByRole("option",{name:"Backup"})).toBeTruthy();expect(screen.getByRole("option",{name:"other"})).toBeTruthy()});
 it("keeps a hanging summary on loading",()=>{vi.stubGlobal("fetch",vi.fn(()=>new Promise(()=>{})));view();expect(screen.getByTestId("list-resource-usage").getAttribute("data-list-phase")).toBe("loading");expect(screen.getByTestId("usage-stat-spend").textContent).toBe("—")});
});
