// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, within, waitFor } from '@testing-library/react';
import { useState } from 'react';
import { withZh } from '@/lib/test-i18n';
import { SettlementPanel } from './settlement-panel';
import { RecoveryPanel } from './recovery-panel';
import { useCommissionOperation, OperationStatus } from './workflow-client';
import type { WorkspaceProps } from './workspace';
vi.mock('next/navigation', () => ({ usePathname: () => '/admin/commission' }));
afterEach(() => { cleanup(); sessionStorage.clear(); vi.unstubAllGlobals(); window.history.replaceState(null,'','/'); });
const json=(body:unknown,status=200)=>({ok:status<400,status,json:async()=>body});
const context={owner_id:'brand-one',owner_code:'品牌一',channel_ids:['channel-one'],channel_codes:{'channel-one':'渠道一'}};
const settlement={id:'cst_alice',status:'settled',amount_minor:1250000,created_at:'2026-10-10T00:00:00Z',period_start:'2026-10-01',period_end:'2026-11-01',beneficiary_role_id:'role_alice',channel_org_id:'channel-one',channel_code:'渠道一',recipient:{email:'alice@example.test',display_name:'Alice'},entries_snapshot_complete:true};
const preview={preview:{id:'preview-one',owner_id:'brand-one',period_start:'2026-10-01',period_end:'2026-11-01',fact_start:'2026-09-01',fact_end:'2026-10-09',entry_count:3,recipient_count:1,settlement_count:1,amount_minor:1250000,min_settle_minor:1000000,ignore_minimum:false,policy_version:'policy-one',groups:[{channel_org_id:'channel-one',beneficiary_role_id:'role_alice',entry_count:3,amount_minor:1250000}],excluded:{frozen:{entry_count:2,amount_minor:100000},below_minimum:{entry_count:1,amount_minor:10000}},expires_at:'2026-10-10T10:00:00Z'},recipients:{role_alice:settlement.recipient},channel_codes:context.channel_codes};
function Harness({view='payout',writable=true,scope='person:brand-one'}:{view?:'pending'|'payout'|'all'|'recovery';writable?:boolean;scope?:string}){
 const [version,setVersion]=useState(0),[params,setParams]=useState(new URLSearchParams(window.location.search));
 const operation=useCommissionOperation(scope,()=>setVersion(v=>v+1));
 const props:WorkspaceProps={scope,context,prefix:'/admin',params,update:values=>{const p=new URLSearchParams(params);Object.entries(values).forEach(([key,v])=>v?p.set(key,v):p.delete(key));window.history.pushState(null,'',`?${p}`);setParams(p);},writable,operation,version};
 return <><OperationStatus operation={operation}/>{view==='recovery'?<RecoveryPanel {...props}/>:<SettlementPanel {...props} view={view}/>}</>;
}
async function payoutForm(){fireEvent.click(await screen.findByRole('button',{name:'登记此单打款'}));const drawer=await screen.findByRole('dialog');await within(drawer).findByText('原结算金额: $1.25 USD · 已冲正金额: $0.00 USD',{exact:false}).catch(()=>{});await waitFor(()=>expect(within(drawer).getByRole('button',{name:'核对并登记'}).matches(':disabled')).toBe(true));fireEvent.click(within(drawer).getByLabelText('我确认这笔打款已实际完成'));fireEvent.click(within(drawer).getByRole('button',{name:'核对并登记'}));return screen.getAllByRole('dialog').at(-1)!;}
it('previews real recipients, exclusions and minimum; confirmed create survives a failed refresh',async()=>{
 let committed=false;const posts:Record<string,unknown>[]=[];
 const fetcher=vi.fn(async(url:unknown,init?:RequestInit)=>{if(init?.method==='POST'){const data=JSON.parse(String(init.body));posts.push(data);committed=true;return json({items:[settlement],operation_id:data.operation_id});}if(String(url).includes('/settlement-preview?'))return json(preview);if(committed)throw new Error('refresh failed');return json({items:[],total:0});});vi.stubGlobal('fetch',fetcher);
 render(withZh(<Harness view="pending"/>));fireEvent.click(await screen.findByRole('button',{name:'结算预览'}));const drawer=screen.getByRole('dialog');await within(drawer).findByText('3 条佣金 · 1 位收款人 · 1 张结算单 · $1.25 USD');expect(within(drawer).getByLabelText('本次忽略最低结算额').matches(':checked')).toBe(false);expect(drawer.textContent).toContain('冻结中 · 2');expect(drawer.textContent).toContain('alice@example.test');fireEvent.click(within(drawer).getByRole('button',{name:'生成结算单'}));fireEvent.click(within(screen.getAllByRole('dialog').at(-1)!).getByRole('button',{name:'确认'}));await screen.findByText(/已确认登记：生成结算单/);expect(posts).toHaveLength(1);expect(posts[0]).toMatchObject({preview_id:'preview-one'});expect(posts[0].operation_id).toBeTruthy();await screen.findByRole('alert');expect(screen.queryByLabelText('原操作结果待确认')).toBeNull();
});
it('lost payout retains its amount, date and identity across remount, conflict and temporary not-found',async()=>{
 const bodies:string[]=[];let mode='lost';vi.stubGlobal('fetch',vi.fn(async(url:unknown,init?:RequestInit)=>{if(init?.method==='POST'){bodies.push(String(init.body));if(mode==='lost')throw new Error('lost');if(mode==='conflict')return json({error:{message:'并发冲突'}},409);return json({item:{...settlement,status:'paid',payout_id:'payout-original'}});}if(String(url).includes('/commission-operations/'))return json({error:{code:'not_found'}},404);if(String(url).includes('/settlements/cst_alice'))return json({item:settlement,entries:[]});return json({items:[settlement],total:1});}));
 const first=render(withZh(<Harness/>));const dialog=await payoutForm();fireEvent.click(within(dialog).getByRole('button',{name:'确认'}));await screen.findAllByText(/结果尚未确认/);expect(JSON.parse(bodies[0])).toMatchObject({amount_minor:1250000,confirmed:true,reference:'',note:''});expect(JSON.parse(bodies[0]).occurred_at).toBeTruthy();first.unmount();render(withZh(<Harness/>));await screen.findByLabelText('原操作结果待确认');fireEvent.click(screen.getByRole('button',{name:'回查原操作'}));await screen.findByText(/暂未查到原记录/);mode='conflict';fireEvent.click(screen.getByRole('button',{name:'重试原操作'}));await screen.findByText('并发冲突');expect(screen.getByLabelText('原操作结果待确认')).toBeTruthy();mode='success';fireEvent.click(screen.getByRole('button',{name:'重试原操作'}));await screen.findByText(/已确认登记：Alice/);expect(bodies).toHaveLength(3);expect(new Set(bodies).size).toBe(1);expect(screen.queryByLabelText('原操作结果待确认')).toBeNull();
});
it('records a partial recovery without a reference and does not classify refresh failure as receipt failure',async()=>{
 const recovery={id:'recovery-one',user_id:'alice',settlement_id:'cst_alice',status:'pending',amount_minor:500000,recovered_minor:100000,created_at:'2026-10-10',recipient:settlement.recipient,receipts:[]};let recorded=false;let payload:Record<string,unknown>={};
 vi.stubGlobal('fetch',vi.fn(async(_url:unknown,init?:RequestInit)=>{if(init?.method==='POST'){payload=JSON.parse(String(init.body));recorded=true;return json({item:{id:'receipt-one',recovery_id:'recovery-one',amount_minor:200000}});}if(recorded)throw new Error('offline');return json({items:[recovery],total:1});}));render(withZh(<Harness view="recovery"/>));fireEvent.click(await screen.findByRole('button',{name:'登记已收回款项'}));const drawer=screen.getByRole('dialog');fireEvent.change(within(drawer).getByLabelText('本次实际收回金额（USD）'),{target:{value:'0.2'}});fireEvent.click(within(drawer).getByLabelText('我确认这笔款项已实际收回'));fireEvent.click(within(drawer).getByRole('button',{name:'核对收回款项'}));const confirm=screen.getAllByRole('dialog').at(-1)!;expect(confirm.textContent).toContain('剩余待收回: $0.20 USD');fireEvent.click(within(confirm).getByRole('button',{name:'确认'}));await screen.findByText(/已确认登记：Alice/);expect(payload).toMatchObject({amount_minor:200000,reference:'',confirmed:true});expect(payload.idempotency_key).toBeTruthy();expect(screen.queryByLabelText('原操作结果待确认')).toBeNull();
});
it('read-only detail preserves original payout and reversal facts without writable controls',async()=>{
 const paid={...settlement,status:'paid',payout_id:'payout-one',payout_reference:'WIRE-1',reversed_minor:300000};vi.stubGlobal('fetch',vi.fn(async(url:unknown)=>String(url).includes('/settlements/cst_alice')?json({item:paid,entries:[{id:'entry-original',amount_minor:1250000,status:'paid',policy_version:'original-policy',usage_event_id:'usage-original'}]}):json({items:[{...paid,settlement_id:'cst_alice'}],total:1})));render(withZh(<Harness view="all" writable={false}/>));fireEvent.click(await screen.findByRole('button',{name:'查看详情'}));const drawer=screen.getByRole('dialog');await within(drawer).findByText(/payout-one.*WIRE-1/);expect(drawer.textContent).toContain('已冲正金额: $0.30 USD');expect(drawer.textContent).toContain('original-policy');expect(screen.queryByRole('button',{name:'核对并登记'})).toBeNull();expect(screen.queryByRole('button',{name:'结算预览'})).toBeNull();fireEvent.click(within(drawer).getByRole('button',{name:'关闭'}));await waitFor(()=>expect(document.activeElement).toBe(screen.getByRole('button',{name:'查看详情'})));
});
it('pages server search while retaining channel and return context',async()=>{
 window.history.replaceState(null,'','/?q=alice&channel_id=channel-one&next=%2Fadmin%2Fdashboard&from=finance');const calls:string[]=[];vi.stubGlobal('fetch',vi.fn(async(url:unknown)=>{calls.push(String(url));return json({items:[settlement],total:151,next_cursor:String(url).includes('cursor=page-two')?'':'page-two'});}));render(withZh(<Harness/>));fireEvent.click(await screen.findByRole('button',{name:'下一页'}));await waitFor(()=>expect(calls.some(url=>url.includes('cursor=page-two'))).toBe(true));const p=new URLSearchParams(window.location.search);expect(p.get('next')).toBe('/admin/dashboard');expect(p.get('from')).toBe('finance');expect(p.get('q')).toBe('alice');expect(p.get('channel_id')).toBe('channel-one');expect(calls.at(-1)).toContain('status=settled');
});
