/** @vitest-environment jsdom */
import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {PendingUsageQueue} from "./pending-usage-queue";
import {withZh} from "@/lib/test-i18n";
vi.mock("@/components/rbac/viewer-context",()=>({useViewer:()=>({userId:"staff",signedIn:true,roles:["platform_admin"]})}));
vi.mock("@/components/brand-context",()=>({useBrand:()=>({id:"brand"})}));
vi.mock("@/components/rbac/if-can",()=>({IfCan:({children}:{children:React.ReactNode})=>children}));
vi.mock("@/components/confirm-button",()=>({ConfirmButton:({children,onConfirm,disabled}:{children:React.ReactNode;onConfirm:()=>unknown;disabled:boolean})=><button disabled={disabled} onClick={()=>void onConfirm()}>{children}</button>}));
vi.mock("@/app/admin/list-panel",()=>({AdminListPanel:({onRowSelect,columns}:{onRowSelect:(r:unknown)=>void;columns:{cell?:({row}:{row:{original:unknown}})=>React.ReactNode}[]})=><div>{["A","B"].map(id=>{const r={id,request_id:id,state:"pending_reconciliation",public_model_id:"Echo",reserved_minor:100};return <div key={id}>{columns[0].cell?.({row:{original:r}})}<button onClick={()=>onRowSelect(r)}>open {id}</button></div>})}</div>}));
function view(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{withZh(<PendingUsageQueue surface="admin"/>)}</QueryClientProvider>)}
const response=(value:unknown)=>({ok:true,json:async()=>value});
describe("pending usage outcomes",()=>{
 beforeEach(()=>{sessionStorage.clear();window.history.replaceState(null,"","/admin/reconciliation")});afterEach(()=>{cleanup();vi.unstubAllGlobals()});
 it("reports actual partial results and keeps only failed selections",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>response({item:{results:[{key:"A",status:"resolved"},{key:"B",status:"failed",error:"already_charged"}]}})));view();await screen.findByRole("checkbox",{name:"选择 A"});fireEvent.click(screen.getByRole("checkbox",{name:"选择 A"}));fireEvent.click(screen.getByRole("checkbox",{name:"选择 B"}));fireEvent.click(screen.getByRole("button",{name:"释放所选预授权"}));await screen.findByText("已关闭 1 条，未完成 1 条。");expect((screen.getByRole("checkbox",{name:"选择 A"}) as HTMLInputElement).checked).toBe(false);expect((screen.getByRole("checkbox",{name:"选择 B"}) as HTMLInputElement).checked).toBe(true);expect(sessionStorage.length).toBe(0)});
 it("restores the same fixed payload and identity after an unknown response",async()=>{const bodies:string[]=[];const ids:string[]=[];let attempt=0;vi.stubGlobal("fetch",vi.fn(async(_url,init)=>{bodies.push(init.body);ids.push(init.headers["Idempotency-Key"]);if(attempt++===0)throw new Error("lost");return response({item:{results:[{key:"A",status:"resolved"}]}})}));view();await screen.findByRole("checkbox",{name:"选择 A"});fireEvent.click(screen.getByRole("checkbox",{name:"选择 A"}));fireEvent.click(screen.getByRole("button",{name:"释放所选预授权"}));await screen.findByText("结果尚未确认，请先核对原请求。");cleanup();view();await screen.findByRole("button",{name:"重试原操作"});expect((screen.getByRole("checkbox",{name:"选择 B"}) as HTMLInputElement).disabled).toBe(true);fireEvent.click(screen.getByRole("button",{name:"重试原操作"}));await screen.findByText("已关闭 1 条，未完成 0 条。");expect(bodies).toEqual([JSON.stringify({ids:["A"]}),JSON.stringify({ids:["A"]})]);expect(ids[0]).toBe(ids[1]);expect(sessionStorage.length).toBe(0)});
 it("does not replace B details with a slower A response",async()=>{let resolveA!:(v:unknown)=>void;vi.stubGlobal("fetch",vi.fn(async(url)=>String(url).includes("/A")?new Promise(resolve=>{resolveA=resolve}):response({item:{id:"B",request_id:"B",state:"pending_reconciliation",public_model_id:"model-B"}})));view();await screen.findByRole("button",{name:"open A"});fireEvent.click(screen.getByRole("button",{name:"open A"}));fireEvent.click(screen.getByRole("button",{name:"open B"}));await screen.findByText("B · model-B");resolveA(response({item:{id:"A",request_id:"A",public_model_id:"model-A"}}));await waitFor(()=>expect(screen.queryByText("A · model-A")).toBeNull());expect(screen.getByRole("link",{name:"打开原请求"}).getAttribute("href")).toContain("/admin/usage/requests/B")});
});
