"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { useTranslations } from "next-intl";
import { useBrand } from "@/components/brand-context";
import {beginOperation,finishOperation,loadOperation,type SavedOperation} from "@/lib/stable-operation";
import { useViewer } from "@/components/rbac/viewer-context";
import { IfCan } from "@/components/rbac/if-can";
import { Button } from "@/components/ui/button";
import { ConfirmButton } from "@/components/confirm-button";
import { Input } from "@/components/ui/input";
import { usageConsole,usageEndpoint,readUsage,type UsageSurface,type RequestReceipt } from "@/components/usage-report";
import { safeReturnHref,appendReturnContext } from "@/lib/return-context";
import { apiBase } from "@/lib/api";
import { confirmHeaders } from "@/lib/confirm";
import { formatUsdMinor } from "@/lib/money";

type Detail={request:RequestReceipt;customer_id?:string;customer?:{id:string;email:string;display_name:string};attempts:{id:string;attempt_no:number;status:string;http_status:number;error_code?:string;latency_ms:number}[];authorization?:{id:string;status:string;amount_minor:number};charges:{charge_id:string;amount_minor:number;state:string}[];commission_status?:string;commissions?:{id:string;usage_event_id:string;beneficiary_role_id:string;settlement_id?:string;amount_minor:number;status:string;policy_version:string;created_at:string}[];usage:{id:string;request_id:string;state:string;customer_amount_minor:number}[]};

type ActionPayload={path:string;body:unknown;kind:string;prompt:string;completion:string};
export function RequestDetail({surface,id}:{surface:UsageSurface;id:string}){
 const t=useTranslations("usageWorkflow"),viewer=useViewer(),brand=useBrand(),client=useQueryClient();
 const base=usageConsole(surface),endpoint=usageEndpoint(surface);
 const [suffix,setSuffix]=useState(""),[returnTo,setReturnTo]=useState(`${base}/usage?tab=requests`),[ready,setReady]=useState(false),[selfHref,setSelfHref]=useState(""),[error,setError]=useState("");
 const [prompt,setPrompt]=useState(""),[completion,setCompletion]=useState(""),[unknown,setUnknown]=useState(false),[pendingKind,setPendingKind]=useState("");
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const scope=new URLSearchParams();if(params.get("channel_id"))scope.set("channel_id",params.get("channel_id")!);setSelfHref(window.location.pathname+window.location.search);setSuffix(scope.size?`?${scope}`:"");setReturnTo(safeReturnHref(params.get("return_to"),`${base}/usage?tab=requests`));setReady(true);},[base,id]);
 const detail=useQuery({queryKey:[viewer.userId,endpoint,"request-detail",id,suffix],queryFn:()=>readUsage<Detail>(`${endpoint}/requests/${encodeURIComponent(id)}${suffix}`),enabled:ready,retry:false});
 const data=detail.data;
 const operationKey=`request-reconcile:${viewer.userId}:${brand?.id||""}:${surface}:${id}:${suffix}`;
 const [operation,setOperation]=useState<SavedOperation<ActionPayload>|null>(null);
 useEffect(()=>{const saved=loadOperation<ActionPayload>(operationKey);setOperation(saved);setUnknown(!!saved);setPendingKind(saved?.payload.kind||"");setPrompt(saved?.payload.prompt||"");setCompletion(saved?.payload.completion||"");setError(saved?t("unknownOutcome"):"")},[operationKey]);
 async function act(path:string,body:unknown){
  const kind=path.includes("/reconcile")?"replay":"release";setError("");
  let saved=operation;
  try{saved=saved||beginOperation(operationKey,{path,body,kind,prompt,completion});setOperation(saved);setPendingKind(saved.payload.kind);setUnknown(true)}catch{setError(t("storageFailed"));return false}
  try{const res=await fetch(`${apiBase}${saved.payload.path}`,{method:"POST",credentials:"include",headers:{...confirmHeaders,"Idempotency-Key":saved.id},body:JSON.stringify(saved.payload.body)});const value=await res.json();if(!res.ok){setError(value.error?.message||t("readFailed"));if(res.status<500){finishOperation(operationKey);setOperation(null);setUnknown(false)}return false};finishOperation(operationKey);setOperation(null);setUnknown(false);await client.invalidateQueries({predicate:q=>q.queryKey.some(v=>typeof v==="string"&&(v.includes("usage")||v.includes("request")||v.includes("dashboard")||v.includes("balance")))});return true;}catch{setError(t("unknownOutcome"));return false}
 }
 const money=(n:number)=>`${formatUsdMinor(n)} USD`;
 function state(value:string){const known=["reserved","settled","released","reversed","pending_reconciliation","committed","confirmed","voided","success","succeeded","failed","running","frozen","paid"];return known.includes(value)?t(value):value}
 return <div className="flex flex-col gap-5"><Link className="text-sm text-brand" href={returnTo}>← {t("back")}</Link><h1 className="text-2xl font-semibold">{t("detail")}</h1>
  {detail.isPending?<p role="status">{t("loading")}</p>:detail.isError?<section role="alert"><p>{t("readFailed")}</p><Button onClick={()=>void detail.refetch()}>{t("retry")}</Button></section>:null}
  {data?<><section className="rounded-card border border-hairline bg-canvas-raised p-5"><dl className="grid gap-4 text-sm sm:grid-cols-2">{[{k:"request",v:data.request.request_id},{k:"model",v:data.request.public_model_id},{k:"result",v:state(data.request.result)},{k:"billing",v:data.request.billing_state?state(data.request.billing_state):!data.charges.length && data.authorization?.status==="released"?t("unbilled"):"—"},{k:"time",v:new Date(data.request.started_at).toLocaleString(undefined,{timeZone:"Asia/Shanghai"})+" · Asia/Shanghai"},{k:"amount",v:money(data.request.customer_amount_minor)}].map(v=><div key={v.k}><dt className="text-ink-mute">{t(v.k)}</dt><dd className="mt-1 break-all">{v.v}</dd></div>)}</dl>
   <div className="mt-4 flex flex-wrap gap-3">{surface!=="user"&&data.customer_id?<Link className="text-brand" href={appendReturnContext(`${base}/users/${encodeURIComponent(data.customer_id)}`,selfHref)}>{t("customer")}{data.customer?` · ${data.customer.display_name||data.customer.email}`:""}</Link>:null}
    {surface==="user"?<><Link href={`/docs?model=${encodeURIComponent(data.request.public_model_id)}&key_id=${encodeURIComponent(data.request.api_key_id||"")}`} className="text-brand">{t("docs")}</Link>{data.request.api_key_id?<Link href={`/app/keys?edit=${encodeURIComponent(data.request.api_key_id)}`} className="text-brand">{t("editKey")}</Link>:null}</>:null}
    {surface==="admin"&&data.charges.some(v=>v.state==="committed")?<IfCan action="billing.refund"><Link href={appendReturnContext(`/admin/billing?request_id=${encodeURIComponent(id)}`,selfHref)} className="text-brand">{t("refund")}</Link></IfCan>:null}
   </div></section>
   <section className="rounded-card border border-hairline bg-canvas-raised p-5"><h2 className="font-semibold">{t("authorization")}</h2>{data.authorization?<dl className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div><dt>{t("billing")}</dt><dd>{state(data.authorization.status)}</dd></div><div><dt>{t("originalReservation")}</dt><dd>{money(data.authorization.amount_minor)}</dd></div><div><dt>{t("reserved")}</dt><dd>{money(["reserved","pending_reconciliation"].includes(data.authorization.status)?data.authorization.amount_minor:0)}</dd></div></dl>:<p className="mt-3 text-sm">{t("noAuthorization")}</p>}</section>
   <section className="rounded-card border border-hairline bg-canvas-raised p-5"><h2 className="font-semibold">{t("attempts")}</h2>{!data.attempts.length?<p>{t("noAttempts")}</p>:<div className="overflow-x-auto"><table className="mt-3 w-full text-left text-sm"><thead><tr>{["attemptNo","result","latency","error"].map(k=><th className="p-2" key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.attempts.map(a=><tr key={a.id}><td className="p-2">{a.attempt_no}</td><td className="p-2">{state(a.status)}</td><td className="p-2">{a.latency_ms}</td><td className="p-2">{a.error_code==="provider_unavailable"||a.error_code==="no_route"?<><span>{t("serviceUnavailable")}</span><details className="text-xs text-ink-mute"><summary>{t("errorCode")}</summary><code>{a.error_code}</code></details></>:a.error_code||"—"}</td></tr>)}</tbody></table></div>}</section>
   <section className="rounded-card border border-hairline bg-canvas-raised p-5"><h2 className="font-semibold">{t("charges")}</h2>{data.charges.length?<ul className="mt-3 space-y-2 text-sm">{data.charges.map(c=><li key={c.charge_id}>{state(c.state)} · {money(c.amount_minor)}<span className="ml-3 font-mono text-xs text-ink-mute">{c.charge_id}</span></li>)}</ul>:<p className="mt-3 text-sm">{t("noCharge")}</p>}</section>
   {surface!=="user"?<section className="rounded-card border border-hairline bg-canvas-raised p-5"><h2 className="font-semibold">{t("commissions")}</h2>{data.commission_status!=="ready"?<p className="mt-3 text-sm">{t(data.commission_status==="read_error"?"read_error":"unavailable")}</p>:!data.commissions?.length?<p className="mt-3 text-sm">{t("noCommission")}</p>:<ul className="mt-3 space-y-3 text-sm">{data.commissions?.map(c=><li key={c.id}>{money(c.amount_minor)} · {state(c.status)}<p>{t("commissionRole")}: <span className="font-mono">{c.beneficiary_role_id}</span> · {t("policy")}: {c.policy_version}</p>{c.settlement_id?<Link className="text-brand" href={appendReturnContext(surface==="admin"?`/admin/commission?tab=payout&settlement_id=${encodeURIComponent(c.settlement_id)}`:viewer.channelType==="C"?`/channel/commission?tab=payout&settlement_id=${encodeURIComponent(c.settlement_id)}`:`/channel/settlements?settlement_id=${encodeURIComponent(c.settlement_id)}`,selfHref)}>{t("settlement")}</Link>:null}</li>)}</ul>}</section>:null}
   {surface==="admin"&&data.usage.some(v=>v.state==="pending_reconciliation")?<IfCan action="usage.resolve"><section className="rounded-card border border-hairline bg-canvas-raised p-5"><h2 className="font-semibold">{t("reconcile")}</h2><p className="my-3 text-sm">{t("replayHelp")}</p>{unknown?<p role="alert" className="my-3 text-sm">{t("unknownOutcome")}</p>:null}<div className="flex flex-wrap gap-3"><label className="grid gap-1 text-sm">{t("prompt")}<Input inputMode="numeric" value={prompt} disabled={unknown} onChange={e=>setPrompt(e.target.value)}/></label><label className="grid gap-1 text-sm">{t("completion")}<Input inputMode="numeric" value={completion} disabled={unknown} onChange={e=>setCompletion(e.target.value)}/></label></div><div className="mt-3 flex flex-wrap gap-3"><ConfirmButton error={error} variant="outline" disabled={unknown&&pendingKind!=="replay"} title={t("replay")} description={`${id} · ${t("prompt")} ${prompt} · ${t("completion")} ${completion}`} validate={()=>/^\d+$/.test(prompt)&&/^\d+$/.test(completion)&&Number.isSafeInteger(Number(prompt))&&Number.isSafeInteger(Number(completion))} onConfirm={()=>act(`${base}/requests/${encodeURIComponent(id)}/reconcile${suffix}`,{usage:{prompt_tokens:Number(prompt),completion_tokens:Number(completion)}})}>{t("replay")}</ConfirmButton><ConfirmButton error={error} variant="outline" title={t("release")} description={`${id} · ${money(data.authorization?.amount_minor||0)}`} disabled={unknown&&pendingKind!=="release"} onConfirm={()=>act(`${base}/usage/pending/resolve${suffix}`,{request_ids:[id]})}>{t("release")}</ConfirmButton></div>{error?<p className="mt-3 text-sm text-danger" role="alert">{error}</p>:null}</section></IfCan>:null}
  </>:null}
 </div>
}
