#!/usr/bin/env node
// 从 backend/openapi/p0.yaml 生成 TypeScript Client。契约变更后必须重跑。
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const specPath = join(root, "..", "backend", "openapi", "p0.yaml");
const outPath = join(root, "lib", "generated", "api.ts");

const yaml = readFileSync(specPath, "utf8");
const paths = [];
let current = "";
for (const line of yaml.split("\n")) {
  const pathMatch = line.match(/^  (\/[A-Za-z0-9_{}/-]+):$/);
  if (pathMatch) {
    current = pathMatch[1];
    continue;
  }
  const op = line.match(/^    (get|post|patch|put|delete):$/);
  if (op && current) {
    paths.push({ method: op[1].toUpperCase(), path: current });
  }
}

const body = `/* eslint-disable */
// Code generated by scripts/generate-client.mjs from backend/openapi/p0.yaml. Do not edit by hand.
export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";

export type GeneratedOperation = {
  method: HttpMethod;
  path: string;
};

export const generatedOperations: GeneratedOperation[] = ${JSON.stringify(paths, null, 2)};

export async function generatedFetch<T>(
  baseURL: string,
  method: HttpMethod,
  path: string,
  init?: RequestInit,
): Promise<T> {
  const response = await fetch(\`\${baseURL}\${path}\`, { ...init, method, cache: "no-store" });
  return (await response.json()) as T;
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body);
console.log(`wrote ${paths.length} operations to ${outPath}`);
