import { expect, test } from "@playwright/test";

test("admin P0 nav renders", async ({ page }) => {
  await page.goto("/admin");
  await expect(page.getByRole("link", { name: "平台管理" })).toBeVisible();
  await expect(page.getByRole("link", { name: "提供商" })).toBeVisible();
  await expect(page.getByRole("link", { name: "套餐审核" })).toBeVisible();
  await expect(page.getByRole("link", { name: "价格" })).toBeVisible();
  await expect(page.getByRole("link", { name: "支付" })).toBeVisible();
  await expect(page.getByRole("link", { name: "指标" })).toBeVisible();
  await expect(page.getByRole("link", { name: "佣金策略" })).toBeVisible();
  await expect(page.getByRole("link", { name: "推广码" })).toBeVisible();
  await expect(page.getByRole("link", { name: "告警" })).toBeVisible();
  await expect(page.getByRole("link", { name: "应急手册" })).toBeVisible();
  await expect(page.getByRole("link", { name: "审计日志" })).toBeVisible();
});

test("admin plan review and commission pages render", async ({ page }) => {
  await page.goto("/admin/plans");
  await expect(page.getByRole("heading", { name: "套餐审核" })).toBeVisible();
  await expect(page.getByRole("button", { name: "待审核" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "创建套餐" })).toBeVisible();
  await expect(page.getByRole("button", { name: "创建套餐" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "下架套餐" })).toBeVisible();
  await expect(page.getByRole("button", { name: "下架套餐" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "续费扫描" })).toBeVisible();
  await expect(page.getByRole("button", { name: "强制到期" })).toBeVisible();
  await expect(page.getByRole("button", { name: "续费扫描" })).toBeVisible();
  await page.goto("/admin/commission");
  await expect(page.getByRole("heading", { name: "佣金策略" })).toBeVisible();
  await expect(page.getByRole("button", { name: "读取策略" })).toBeVisible();
  await page.goto("/admin/payments");
  await expect(page.getByRole("heading", { name: "支付", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "确认支付" })).toBeVisible();
  await page.goto("/admin/prices");
  await expect(page.getByRole("heading", { name: "价格", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "发布价格" })).toBeVisible();
  await page.goto("/admin/metrics");
  await expect(page.getByRole("heading", { name: "运营看板" })).toBeVisible();
  await page.goto("/admin/users");
  await expect(page.getByRole("heading", { name: "用户/项目" })).toBeVisible();
  await expect(page.getByLabel("操作原因")).toBeVisible();
  await page.goto("/admin/alerts");
  await expect(page.getByRole("heading", { name: "告警" })).toBeVisible();
  await expect(page.getByRole("button", { name: "评估告警" })).toBeVisible();
  await page.goto("/admin/runbooks");
  await expect(page.getByRole("heading", { name: "应急手册" })).toBeVisible();
  await page.goto("/admin/billing");
  await expect(page.getByRole("heading", { name: "余额 / 充值 / 账务" })).toBeVisible();
  await expect(page.getByRole("button", { name: "赠送额度" })).toBeVisible();
  await page.goto("/admin/channels");
  await expect(page.getByRole("heading", { name: "渠道租户" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "新建渠道" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "渠道" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "代理商" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "KOL" })).toBeVisible();
  await expect(page.getByText("不能自己添加提供商和模型")).toBeVisible();
  await page.getByRole("button", { name: "新建渠道" }).click();
  await expect(page.getByRole("heading", { name: "创建渠道" })).toBeVisible();
  await expect(page.getByRole("button", { name: "创建渠道" })).toBeVisible();
  await page.getByRole("button", { name: "关闭" }).click();
  await page.getByRole("tab", { name: "代理商" }).click();
  await expect(page.getByRole("heading", { name: "代理商" })).toBeVisible();
  await expect(page.getByRole("button", { name: "新建代理商" })).toBeVisible();
  await page.getByRole("tab", { name: "KOL" }).click();
  await expect(page.getByRole("heading", { name: "KOL", exact: true })).toBeVisible();
  await page.goto("/admin/channels/chn_reseller_b");
  await expect(page.getByRole("heading", { name: "渠道详情" })).toBeVisible();
  await expect(page.getByRole("link", { name: "返回列表" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "平台模型白名单" })).toBeVisible();
  await expect(page.getByText("租户不能自己添加提供商和模型")).toBeVisible();
  await expect(page.getByRole("button", { name: "从平台目录授权" })).toBeVisible();
  await expect(page.getByRole("link", { name: "模型" }).first()).toBeVisible();
  await expect(page.getByRole("heading", { name: "收款就绪" })).toBeVisible();
  await expect(page.getByText("停用后冻结新消费")).toBeVisible();
  await page.getByRole("button", { name: "编辑" }).click();
  await expect(page.getByRole("button", { name: "保存渠道" })).toBeVisible();
  await page.goto("/admin/partners/acr_b_agent");
  await expect(page.getByRole("heading", { name: "代理商详情" })).toBeVisible();
  await expect(page.getByText("不能自建提供商或模型")).toBeVisible();
  await page.goto("/admin/commission");
  await expect(page.getByRole("heading", { name: "手工结算" })).toBeVisible();
  await expect(page.getByRole("button", { name: "人工打款" })).toBeVisible();
  await page.goto("/admin/settings");
  await expect(page.getByRole("heading", { name: "管理员 2FA" })).toBeVisible();
  await expect(page.getByRole("button", { name: "读取 2FA" })).toBeVisible();
  await expect(page.getByRole("button", { name: "开始绑定" })).toBeVisible();
  await expect(page.getByRole("button", { name: "确认启用" })).toBeVisible();
  await expect(page.getByRole("button", { name: "关闭 2FA" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "运维开关" })).toBeVisible();
  await expect(page.getByRole("button", { name: "健康探测" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "备份演练" })).toBeVisible();
  await expect(page.getByRole("button", { name: "备份演练" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "异常演练" })).toBeVisible();
  await expect(page.getByRole("button", { name: "支付演练" })).toBeVisible();
  await expect(page.getByRole("button", { name: "媒体演练" })).toBeVisible();
  await expect(page.getByRole("button", { name: "TLS 演练" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "OEM 证书" })).toBeVisible();
  await expect(page.getByRole("button", { name: "签发证书" })).toBeVisible();
  await page.goto("/admin/routes");
  await expect(page.getByRole("heading", { name: "创建路由" })).toBeVisible();
  await expect(page.getByRole("button", { name: "创建路由" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "改路由策略" })).toBeVisible();
  await expect(page.getByRole("button", { name: "保存策略" })).toBeVisible();
  await page.goto("/admin/commission");
  await expect(page.getByRole("heading", { name: "佣金重算" })).toBeVisible();
  await expect(page.getByRole("button", { name: "重算佣金" })).toBeVisible();
  await page.goto("/admin/usage");
  await expect(page.getByRole("heading", { name: "用量回放" })).toBeVisible();
  await expect(page.getByRole("button", { name: "回放 usage" })).toBeVisible();
  await page.goto("/admin/promos");
  await expect(page.getByRole("heading", { name: "推广角色" })).toBeVisible();
  await expect(page.getByRole("button", { name: "创建推广码" })).toBeVisible();
  await page.goto("/admin/providers");
  await expect(page.getByRole("heading", { name: "提供商" })).toBeVisible();
  await expect(page.getByText("列表每行可探测")).toBeVisible();
  await expect(page.getByRole("heading", { name: "凭据轮换" })).toBeVisible();
  await expect(page.getByRole("button", { name: "轮换凭据" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "账号池" })).toBeVisible();
  await expect(page.getByRole("button", { name: "读取账号" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "改 Provider 状态" })).toBeVisible();
  await expect(page.getByRole("button", { name: "保存 Provider" })).toBeVisible();
  await page.goto("/admin/audit");
  await expect(page.getByRole("heading", { name: "Outbox 与探测" })).toBeVisible();
  await expect(page.getByRole("button", { name: "读取 Outbox" })).toBeVisible();
  await expect(page.getByRole("button", { name: "写入探测" })).toBeVisible();
  await page.goto("/admin/keys");
  await expect(page.getByRole("heading", { name: "禁用 API Key" })).toBeVisible();
  await expect(page.getByRole("button", { name: "禁用 Key" })).toBeVisible();
  await page.goto("/admin/models");
  await expect(page.getByRole("heading", { name: "模型审核" })).toBeVisible();
  await expect(page.getByRole("button", { name: "待审核" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "创建模型" })).toBeVisible();
  await expect(page.getByRole("button", { name: "创建模型" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "挂载 Provider" })).toBeVisible();
  await expect(page.getByRole("button", { name: "挂载" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "弃用模型" })).toBeVisible();
  await expect(page.getByRole("button", { name: "弃用模型" })).toBeVisible();
  await page.goto("/admin/models/tokenhub/echo-1");
  await expect(page.getByRole("heading", { name: "编辑属性" })).toBeVisible();
  await expect(page.getByRole("button", { name: "保存属性" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "定价" })).toBeVisible();
  await expect(page.getByRole("button", { name: "发布价格" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "上架" })).toBeVisible();
  await expect(page.getByRole("button", { name: "拒绝" })).toBeVisible();
  await expect(page.getByRole("button", { name: "通过" })).toBeVisible();
  await expect(page.getByRole("button", { name: "发布", exact: true })).toBeVisible();
});
