import { expect, test } from "@playwright/test";

test("admin P0 nav renders", async ({ page }) => {
  await page.goto("/admin");
  await expect(page.getByRole("link", { name: "平台管理" })).toBeVisible();
  await expect(page.getByRole("link", { name: "提供商" })).toBeVisible();
  await expect(page.getByRole("link", { name: "套餐审核" })).toBeVisible();
  await expect(page.getByRole("link", { name: "价格" })).toBeVisible();
  await expect(page.getByRole("link", { name: "支付" })).toBeVisible();
  await expect(page.getByRole("link", { name: "指标" })).toBeVisible();
  await expect(page.getByRole("link", { name: "佣金策略" })).toBeVisible();
  await expect(page.getByRole("link", { name: "推广码" })).toBeVisible();
  await expect(page.getByRole("link", { name: "告警" })).toBeVisible();
  await expect(page.getByRole("link", { name: "应急手册" })).toBeVisible();
  await expect(page.getByRole("link", { name: "审计日志" })).toBeVisible();
});

test("admin plan review and commission pages render", async ({ page }) => {
  await page.goto("/admin/plans");
  await expect(page.getByRole("heading", { name: "套餐审核" })).toBeVisible();
  await expect(page.getByRole("button", { name: "待审核" })).toBeVisible();
  await page.goto("/admin/commission");
  await expect(page.getByRole("heading", { name: "佣金策略" })).toBeVisible();
  await expect(page.getByRole("button", { name: "读取策略" })).toBeVisible();
  await page.goto("/admin/payments");
  await expect(page.getByRole("heading", { name: "支付", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "确认支付" })).toBeVisible();
  await page.goto("/admin/prices");
  await expect(page.getByRole("heading", { name: "价格", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "发布价格" })).toBeVisible();
  await page.goto("/admin/metrics");
  await expect(page.getByRole("heading", { name: "运营看板" })).toBeVisible();
  await page.goto("/admin/users");
  await expect(page.getByRole("heading", { name: "用户/项目" })).toBeVisible();
  await expect(page.getByLabel("操作原因")).toBeVisible();
  await page.goto("/admin/alerts");
  await expect(page.getByRole("heading", { name: "告警" })).toBeVisible();
  await expect(page.getByRole("button", { name: "评估告警" })).toBeVisible();
  await page.goto("/admin/runbooks");
  await expect(page.getByRole("heading", { name: "应急手册" })).toBeVisible();
  await page.goto("/admin/billing");
  await expect(page.getByRole("heading", { name: "余额 / 充值 / 账务" })).toBeVisible();
  await expect(page.getByRole("button", { name: "赠送额度" })).toBeVisible();
  await page.goto("/admin/channels");
  await expect(page.getByRole("heading", { name: "渠道额度" })).toBeVisible();
  await expect(page.getByRole("button", { name: "调整额度" })).toBeVisible();
  await page.goto("/admin/commission");
  await expect(page.getByRole("heading", { name: "手工结算" })).toBeVisible();
  await expect(page.getByRole("button", { name: "人工打款" })).toBeVisible();
  await page.goto("/admin/settings");
  await expect(page.getByRole("heading", { name: "运维开关" })).toBeVisible();
  await expect(page.getByRole("button", { name: "健康探测" })).toBeVisible();
  await page.goto("/admin/usage");
  await expect(page.getByRole("heading", { name: "用量回放" })).toBeVisible();
  await expect(page.getByRole("button", { name: "回放 usage" })).toBeVisible();
  await page.goto("/admin/promos");
  await expect(page.getByRole("heading", { name: "推广角色" })).toBeVisible();
  await expect(page.getByRole("button", { name: "创建推广码" })).toBeVisible();
  await page.goto("/admin/providers");
  await expect(page.getByRole("heading", { name: "提供商" })).toBeVisible();
  await expect(page.getByText("列表每行可探测")).toBeVisible();
  await expect(page.getByRole("heading", { name: "凭据轮换" })).toBeVisible();
  await expect(page.getByRole("button", { name: "轮换凭据" })).toBeVisible();
});
