// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,within,waitFor} from '@testing-library/react';
import {withZh} from '@/lib/test-i18n';
import {AdminSupplierPanel} from './supplier-panel';
const viewer=vi.hoisted(()=>({userId:'finance',roles:['finance_admin'],signedIn:true,loading:false}));
vi.mock('@/components/rbac/viewer-context',()=>({useViewer:()=>viewer}));
vi.mock('next/navigation',()=>({usePathname:()=>'/admin/billing'}));
afterEach(()=>{cleanup();sessionStorage.clear();vi.unstubAllGlobals();viewer.roles=['finance_admin'];window.history.replaceState(null,'','/');});
const json=(body:unknown,status=200)=>({ok:status<400,status,json:async()=>body});
const context={owner_id:'owner',owner_name:'品牌一',channel_ids:['owner'],channel_codes:{owner:'品牌一'}};
const row={id:'supplier-original',channel_org_id:'owner',amount_minor:-250000,currency:'USD',vendor_name:'供应商甲',source_type:'provider_invoice',occurred_at:'2026-10-09T00:00:00Z',created_at:'2026-10-10T00:00:00Z',actor_email:'finance@example.test',actor_user_id:'finance',status:'recorded'};
it('requires an actual payment and records optional proof; confirmed receipt survives a failed refresh',async()=>{
 let committed=false;let payload:Record<string,unknown>={};vi.stubGlobal('fetch',vi.fn(async(_url:unknown,init?:RequestInit)=>{if(init?.method==='POST'){payload=JSON.parse(String(init.body));committed=true;return json({item:{...row,idempotency_key:payload.idempotency_key}});}if(committed)throw new Error('refresh');return json({items:[],total:0});}));render(withZh(<AdminSupplierPanel context={context}/>));fireEvent.click(await screen.findByRole('button',{name:'登记支出'}));const drawer=screen.getByRole('dialog');fireEvent.change(within(drawer).getByLabelText('付款对象'),{target:{value:'供应商甲'}});fireEvent.change(within(drawer).getByLabelText('实际付款金额（USD）'),{target:{value:'0.25'}});expect(within(drawer).getByRole('button',{name:'核对支出'}).matches(':disabled')).toBe(true);fireEvent.click(within(drawer).getByLabelText('我确认款项已实际支付'));fireEvent.click(within(drawer).getByRole('button',{name:'核对支出'}));const confirm=screen.getAllByRole('dialog').at(-1)!;expect(confirm.textContent).toContain('品牌一');expect(confirm.textContent).toContain('$0.25 USD');fireEvent.click(within(confirm).getByRole('button',{name:'确认'}));await screen.findByText(/已确认登记：供应商甲/);expect(payload).toMatchObject({amount_minor:250000,currency:'USD',vendor_name:'供应商甲',bank_ref:'',memo:'',confirmed:true});expect(payload.occurred_at).toBeTruthy();expect(payload.idempotency_key).toBeTruthy();await screen.findByRole('alert');expect(screen.queryByLabelText('原操作结果待确认')).toBeNull();
});
it('keeps an unknown reversal identity through remount, absent lookup and conflict; rejects a mismatched lookup',async()=>{
 let mode='lost',opID='';const requests:string[]=[];vi.stubGlobal('fetch',vi.fn(async(url:unknown,init?:RequestInit)=>{if(init?.method==='POST'){requests.push(String(init.body));opID=JSON.parse(String(init.body)).operation_id;if(mode==='lost')throw new Error('lost');if(mode==='conflict')return json({error:{message:'原记录冲突'}},409);return json({item:{...row,id:'reversal-original',amount_minor:250000,reversal_of:row.id,memo:'重复登记',idempotency_key:opID}});}if(String(url).includes('operation_id='))return mode==='mismatch'?json({item:{...row,idempotency_key:opID}}):json({operation_status:'not_found'});return json({items:[row],total:1});}));const first=render(withZh(<AdminSupplierPanel context={context}/>));fireEvent.click(await screen.findByRole('button',{name:'查看详情'}));const drawer=screen.getByRole('dialog');fireEvent.change(within(drawer).getByLabelText('冲正原因'),{target:{value:'重复登记'}});fireEvent.click(within(drawer).getByRole('button',{name:'冲正支出'}));fireEvent.click(within(screen.getAllByRole('dialog').at(-1)!).getByRole('button',{name:'确认'}));await screen.findByLabelText('原操作结果待确认');first.unmount();render(withZh(<AdminSupplierPanel context={context}/>));fireEvent.click(await screen.findByRole('button',{name:'回查原操作'}));await screen.findByText(/暂未查到原记录/);mode='mismatch';fireEvent.click(screen.getByRole('button',{name:'回查原操作'}));await waitFor(()=>expect(screen.getByLabelText('原操作结果待确认')).toBeTruthy());mode='conflict';fireEvent.click(screen.getByRole('button',{name:'重试原操作'}));await screen.findByText('原记录冲突');mode='success';fireEvent.click(screen.getByRole('button',{name:'重试原操作'}));await screen.findByText(/已确认登记：供应商甲/);expect(new Set(requests).size).toBe(1);expect(JSON.parse(requests[0])).toMatchObject({reason:'重复登记',operation_id:opID});
});
it('allows an auditor to inspect actual original facts without payment or correction controls',async()=>{
 viewer.roles=['audit_readonly'];vi.stubGlobal('fetch',vi.fn(async()=>json({items:[row],total:1,next_cursor:'page2'})));render(withZh(<AdminSupplierPanel context={context}/>));fireEvent.click(await screen.findByRole('button',{name:'查看详情'}));const drawer=screen.getByRole('dialog');expect(drawer.textContent).toContain('finance@example.test');expect(screen.queryByRole('button',{name:'登记支出'})).toBeNull();expect(screen.queryByRole('textbox',{name:'冲正原因'})).toBeNull();expect(within(drawer).queryByRole('button',{name:'冲正支出'})).toBeNull();
});
